### ISSUE TITLE
Use master for all builds

### ISSUE THREAD

**Issue by frankivo** [frankivo/scala-ms-exchange#5]
Currently there is a seperate 2.11 branch to do builds compatible with Apache Spark.
Look into https://github.com/prokod/gradle-crossbuild-scala

My main concern: there have been code changes for to be able to compile with 2.11 (asScala)

**Comment by frankivo** [comment]
Upstream issue: https://github.com/prokod/gradle-crossbuild-scala/issues/70

**Comment by frankivo** [comment]
Crossbuild compilation errors have been resolved in #13 
Now I have to look into scaladocs and sources jars with crossbuild.
